### ISSUE TITLE
[Tutorial proposal] First day of snow

### ISSUE THREAD

**Issue by gino-m** [google/earthengine-community#162]
**What is the objective of the proposed tutorial?**
A clear and concise description of what users can expect to learn from your tutorial.

**What is the scope of the proposed tutorial?**
The thematic (forestry, water resources, land cover classification, Earth Engine core libraries, etc) and specific geographic area, if relevant.

**Please provide an outline of the structure of the proposed tutorial?**
1. Section 1
  a. Subsection 1a
  b. Subsection 1b
2. Section 2
  .. et cetera. ..

**In what format will you be submitting the tutorial?**
Select one: [Markdown](https://guides.github.com/features/mastering-markdown/) or [Colab](https://research.google.com/colaboratory/faq.html)

This request will be reviewed by the Earth Engine community maintainers, who will reply on this issue tracker with any questions or suggestions. Once approved, this issue will be assigned to you and you can begin work on the tutorial following instructions in [Writing a tutorial](https://developers.google.com/earth-engine/tutorials/community/write). When ready, enter “Closes #issueno” in the description of your Pull Request to link the tutorial to this issue.

Issue labels:
proposal, tutorial

**Comment by gino-m** [comment]
Hi @aharmstrong! Thanks for the tutorial in #161! Could you kindly provide the info above so we can vet it before proceeding? Thanks!

**Comment by jdbcode** [comment]
@gino-m I'd like to request that tutorial [#161](https://github.com/google/earthengine-community/pull/161) be exempt from the proposal step. @aharmstrong and I have been collaborating on it since before the proposal step was implemented.

@aharmstrong, before beginning work on future tutorials, please submit a [proposal](https://developers.google.com/earth-engine/tutorials/community/write#proposing_a_tutorial) first.

**Comment by gino-m** [comment]
Sure! Sorry I didn't realize you'd already been discussing this before we introduced this new process. Please disregard!
