### ISSUE TITLE
Issue with tutorials/identifying-first-day-no-snow/index.md

### ISSUE THREAD

**Issue by webb-e** [google/earthengine-community#298]
The following code forces the `millis `band to be a 16-bit integer (even though you'd think the code` .set('millis', millis)` would solve this problem). 

`img.addBands(dateBands).toInt16().set('millis', millis) `

instead, this code will do the trick:
```
  return img.addBands(dateBands)
            .cast({'calDoy': 'int'}).cast({'millis': 'long'}).cast({'year': 'int'})
```

Additionally, it might be helpful to note that one can determine the first day of snow in the fall by using modifying the tutorial in one very minor way-- just reverse sort the `millis `band (`.sort('millis', false)`)

**Comment by jdbcode** [comment]
@webb-e thanks for catching the millis band type issue and the simple suggestion for an alternative analysis! What do you think about forking the repo, making the changes, and submitting a pull request? We'd love for you to be a contributor!

**Comment by webb-e** [comment]
@jdbcode  Done! Let me know if that's what you were thinking,

**Comment by jdbcode** [comment]
Thanks for doing it @webb-e! However it looks like the merge was from a branch into your fork of the repo, which is fine, but you'll need to do one more step to request the code get pulled into the Google repo. From your repo, you should see a "Pull request" button - hit it.

![image](https://user-images.githubusercontent.com/9044197/109680110-073d3d80-7b31-11eb-9f91-aaff6b233ffc.png)

Make sure that your repo is pointing into the Google repo

![image](https://user-images.githubusercontent.com/9044197/109680295-3a7fcc80-7b31-11eb-8df5-fbb3158e9127.png)

Then hit the "Create pull request" button, provide a pull request title (something like "Snow tutorial edit"), and add "Closes issue #298" to the description. Then submit the request. Sometimes there are conflicts, but we'll deal with that if it comes up.

As for the changes, they look fine, I have just two small nits that I'll describe once the pull request is registered.

**Comment by jdbcode** [comment]
FYI -- The changes in #299 should be merged and published to the Earth Engine Developer Guide within a week.

**Comment by jdbcode** [comment]
@webb-e thanks again for the edits!
Changes are now live: https://developers.google.com/earth-engine/tutorials/community/identifying-first-day-no-snow

**Comment by webb-e** [comment]
Hey @jdbcode  I was running this code for my own work. It turns out that you need the `.set('millis', millis)`  line in order for the `.sort` function to work. Perhaps you can shed light on why....if you don't `.set('millis', millis) `, the millis values are recorded correctly, but for whatever reason, the `.sort('millis', false)` doesn't see that....

**Comment by jdbcode** [comment]
It appears that there is no 'millis' property being set in the `addDateBands` function so sorting on it is not doing anything i.e. there is no 'millis' property (oops). By default the collection should be in ascending order by observation time, which is why the logic should be working when identifying the first day of no snow.

Adding `.set('millis', millis)` to the returned image in `addDateBands` function should resolve it (as you are suggesting, I think?)  

```
return img.addBands(dateBands)
    .cast({'calDoy': 'int', 'relDoy': 'int', 'millis': 'long','year': 'int'})
   .set('millis', millis); 
```
Would you mind creating a new issue for the topic of last day with 0 snow, testing the 'millis' prop setting to see if that works as you expect, and make another pull request for the change?

I'm now having doubts about how this works? The magic is in `.reduce(ee.Reducer.min(5))`; it is finding pixels that have 0 percent snow cover, but in the annual time series, for a given pixel, there will be many observations that are 0, so it has to pick one of the observations... I think it is then relying on the collection order and selecting the first in the collection that matches the min criteria. I vaguely remember testing this, but I'm not completely confident now. I'll try to verify it in the next few days.

**Comment by webb-e** [comment]
Yes, in my tests adding `.set('millis', millis)` fixes the problem. 

My understanding of how this works is the same as yours. First put all the images in order, and then find the first pixel that has 0% snow cover (`.reduce(ee.Reducer.min(5))` does this). And yes, since the collections are sorted chronologically anyway, so not having the 'millis' band does not affect finding the first day of no snow. I encountered the issue when I reverse-sorted (without a 'millis' band, the `sort()` doesn't sort by date (but also does not throw an error). 

I will create a new issue and new pull request.

**Comment by webb-e** [comment]
What I don't understand is the `addDateBands` function seems to be adding a 'millis' band and you can get the 'millis' value for each pixel but without the `.set('millis', millis)` part, the `sort` function doesn't work.

**Comment by jdbcode** [comment]
Because there is no 'millis' image property to sort on. The millis value is encoded in the image band only (at this point). The `.sort` method is not sorting on pixel values, it is sorting on image property values. So, a 'millis' property value needs to be added to each image, in addition to having the millis encoded as a band.

**Comment by webb-e** [comment]
Ahhh ok thank you.

**Comment by jdbcode** [comment]
Changes are live: https://developers.google.com/earth-engine/tutorials/community/identifying-first-day-no-snow

Thanks, Elizabeth!
