### ISSUE TITLE
when i get the ndvi for the latest time with python api, return none list,

### ISSUE THREAD

**Issue by drunk-bird** [google/earthengine-community#805]
when I get the ndvi for the latest time with python api, return none list, but javascript can get the data. follow is my codes:
ndvi = ee.ImageCollection("MODIS/006/MYD13Q1")\
         .filter(ee.Filter.date('2023-07-01','2023-08-01'))\
         .select('NDVI')

ndviVis = {
  'min': 0,
  'max': 8000,
  'palette': [
    'ffffff', 'ce7e45', 'df923d', 'f1b555', 'fcd163', '99b718', '74a901',
    '66a000', '529400', '3e8601', '207401', '056201', '004c00', '023b01',
    '012e01', '011d01', '011301'
  ],
}

len(ndvi.getInfo()['features'])

##return
0

**Comment by jdbcode** [comment]
It looks like that data has not been processed since 2023-02-10: 
https://code.earthengine.google.com/53060f21273dffbf3c3022a147e60441

Which may be a result of the provider ending version 6: https://lpdaac.usgs.gov/news/modis-version-6-forward-processing-ends-february-15-2023/

You should use version 6.1: "MODIS/061/MYD13Q1"

If you have a concern, please report the issue here: https://issuetracker.google.com/issues/new?component=1161653&template=1662291
